<?php

namespace app\services\exporters\builders;

use Yii;

class CsvFieldsBuilder
{
    /**
     * @return array
     */
    public function getHeadFields(): array
    {
        return [
            Yii::t('app', 'Date'),
            Yii::t('app', 'User'),
            Yii::t('app', 'Type'),
            Yii::t('app', 'Event'),
            Yii::t('app', 'Message'),
        ];
    }

    /**
     * @param $values
     * @return array
     */
    public function buildCswRowDate($values): array
    {
        return [
            $this->buildDate($values['ins_ts']),
            $this->buildUser($values['user']),
            $values['object'],
            $values['event'],
            $this->buildMessage($values)
        ];
    }

    /**
     * @param $value
     * @return string
     */
    private function buildDate($value): string
    {
        return $value;
    }

    /**
     * @param ?array $value
     * @return string
     */
    private function buildUser(?array $value): string
    {
        return $value ? $value['username']
                      : Yii::t('app', 'System');
    }


    /**
     * @param array $values
     * @return string
     */
    private function buildMessage(array $values): string
    {
        // TODO переписать хелпер таким образом, чтобы получить данные без использования объектов ActiveRecord
        // strip_tags(HistoryListHelper::getBodyByModel($model))
        return 'Some message generated by HistoryListHelper';
    }
}
